# Generated by Django 5.0 on 2024-10-07 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vital_care_app', '0003_user_role_doctor_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='speciality',
            new_name='specialist',
        ),
    ]
