# Generated by Django 5.0 on 2024-10-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_care_app', '0004_rename_speciality_doctor_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.CharField(max_length=3),
        ),
    ]
