# Generated by Django 5.0 on 2024-10-10 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_care_app', '0011_portal_items_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal_items',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vital_care_app.portal'),
        ),
    ]
