# Generated by Django 5.0 on 2024-10-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_care_app', '0018_alter_patient_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='preferred_date',
            field=models.DateField(max_length=10),
        ),
    ]
