# Generated by Django 5.0 on 2024-10-11 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_care_app', '0021_appointment_is_approved_doc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='payment',
            new_name='amount_to_be_paid',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
