# Generated by Django 5.0 on 2024-10-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_care_app', '0022_rename_payment_appointment_amount_to_be_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='preferred_date',
            field=models.CharField(max_length=10),
        ),
    ]
