# Generated by Django 5.0 on 2024-10-11 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_care_app', '0023_alter_appointment_preferred_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Spec_doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=200)),
                ('specialist_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vital_care_app.specialist')),
            ],
        ),
    ]
