# Generated by Django 5.0 on 2024-10-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_care_app', '0027_portal_items_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal_items',
            name='order',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
