# Generated by Django 5.0 on 2024-10-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_care_app', '0032_appointment_visited_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
