# Generated by Django 5.0 on 2024-10-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_care_app', '0033_appointment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
