# Generated by Django 5.0 on 2024-10-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vital_care_app', '0035_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='total_quantity',
        ),
    ]
