# Generated by Django 5.0 on 2024-10-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_care_app', '0039_prescription_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_prescribed',
            field=models.BooleanField(default=False),
        ),
    ]
