# Generated by Django 5.0 on 2024-11-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vital_care_app', '0045_blood_group_gender_alter_patient_last_name'),
        ('vital_care_app', '0046_appointment_is_deleted'),
    ]

    operations = [
    ]
