services:
  - type: web
    name: vital_care
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn vital_care.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: vital_care.settings