# Generated by Django 5.0 on 2024-10-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_care_app', '0006_alter_doctor_user_alter_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='age',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
