# Generated by Django 5.0 on 2024-10-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_care_app', '0007_doctor_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
