# Generated by Django 5.0 on 2024-10-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_care_app', '0013_alter_portal_items_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='consultation_fee',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
    ]
