# Generated by Django 5.0 on 2024-10-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_care_app', '0015_alter_patient_date_of_birth_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.CharField(max_length=20),
        ),
    ]
