# Generated by Django 5.0 on 2024-10-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_care_app', '0019_alter_appointment_preferred_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='speciality',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
