# Generated by Django 5.0 on 2024-10-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_care_app', '0020_appointment_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_approved_doc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_approved_recep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
    ]
