# Generated by Django 5.0 on 2024-10-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vital_care_app', '0025_doctor_spec_id_delete_spec_doc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='spec_id',
            new_name='spec',
        ),
    ]
