# Generated by Django 5.0 on 2024-10-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_care_app', '0026_rename_spec_id_doctor_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal_items',
            name='icon',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
