# Generated by Django 5.0 on 2024-10-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_care_app', '0028_portal_items_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='remark',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
