# Generated by Django 5.0 on 2024-10-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_care_app', '0029_appointment_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='remark',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
