# Generated by Django 5.0 on 2024-10-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_care_app', '0031_appointment_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='visited_doc',
            field=models.BooleanField(default=False),
        ),
    ]
