# Generated by Django 5.0 on 2024-10-14 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_care_app', '0034_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=255)),
                ('medicine', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=255)),
                ('quantity_per_day', models.CharField(max_length=255)),
                ('total_quantity', models.CharField(max_length=255)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vital_care_app.appointment')),
            ],
        ),
    ]
