# Generated by Django 5.0 on 2024-10-14 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vital_care_app', '0036_remove_prescription_total_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='diagnosis',
            new_name='instruction',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='quantity_per_day',
            new_name='quantity',
        ),
    ]
