# Generated by Django 5.0 on 2024-10-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vital_care_app', '0037_rename_diagnosis_prescription_instruction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='quantity',
            new_name='days',
        ),
    ]
