# Generated by Django 5.0 on 2024-10-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_care_app', '0038_rename_quantity_prescription_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
