# Generated by Django 5.0 on 2024-10-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vital_care_app', '0044_alter_patient_date_of_birth'),
    ]

    operations = [
        
    ]
